[engine]
env = [
  "ALL_PROXY=socks5h://127.0.0.1:12138",
  "all_proxy=socks5h://127.0.0.1:12138",
  "HTTP_PROXY=socks5h://127.0.0.1:12138",
  "HTTPS_PROXY=socks5h://127.0.0.1:12138",
  "http_proxy=socks5h://127.0.0.1:12138",
  "https_proxy=socks5h://127.0.0.1:12138",
  "NO_PROXY=localhost,127.0.0.1",
  "no_proxy=localhost,127.0.0.1"
]