#!/bin/sh

exec /usr/bin/podman run \
  --replace \
  --rm \
  --name=nginx \
  --network=host \
  -v /data/appdata/nginx/conf.d:/etc/nginx/conf.d:Z \
  -v /data/appdata/nginx/nginx.conf:/etc/nginx/nginx.conf:Z \
  -v /data/www:/usr/share/nginx/html:ro,z \
  docker.io/nginx:latest