[global]
   workgroup = WORKGROUP
   logging = file
[data]
   path = /data
   valid users = huai
   writable = yes
   force user = root
   force group = root
   create mask = 0644
   directory mask = 0755   
