[global]
   workgroup = WORKGROUP
   server string = Samba Server
   server role = standalone server
   security = user
   logging = file
   map to guest = never
[data]
   path = /data
   valid users = huai
   writable = yes
   force user = root
   force group = root
   create mask = 0644
   directory mask = 0755   
