#!/bin/sh
exec 2>&1

# Use sing-box instead of mihomo
exec /usr/bin/podman run \
  --replace \
  --rm \
  --name=sing-box \
  --net=host \
  -v /data/appdata/sing-box:/etc/sing-box:Z \
  ghcr.io/sagernet/sing-box:latest \
  run -D /etc/sing-box/