#!/bin/sh

exec /usr/bin/podman run \
  --replace \
  --rm \
  --name=webdav \
  -e WEBDAV_CONFIG=/config.yaml \
  -p 6065:6065 \
  -v /data/webdav:/srv:Z \
  -v /data/appdata/webdav/config.yaml:/config.yaml:Z \
  docker.io/hacdias/webdav:latest