volume=50
# hwdec=d3d11va
vo=gpu
# Disable heavy scaling algorithms
profile=fast

# Force A/V sync to audio (helps with VFR videos)
video-sync=audio

# Try copy-back hardware decoding for better compatibility
hwdec=d3d11va-copy