#!/bin/sh
exec 2>&1

exec /usr/bin/podman run \
  --replace \
  --rm \
  --name=emby \
  --net=host \
  -v /data/appdata/emby:/config:Z \
  -v /data/media:/media:z \
  lscr.io/linuxserver/emby:latest
