#!/bin/sh
exec /usr/bin/podman run \
  --replace \
  --rm \
  --name=aria2 \
  -p 6800:6800 \
  -e RPC_SECRET=123123 \
  -e RPC_PORT=6800 \
  -v /data/appdata/aria2:/config:Z \
  -v /data/www/Downloads:/downloads:z \
  docker.io/p3terx/aria2-pro:latest
